### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by SquirrelRat** [IlliumIv/Cheat-Sheets#1]
An error with "_MeasureText = new MeasureTextDelegate(Graphics.MeasureText(string text));"

"string text" 

CheatSheetsCore.cs(61,73) : error CS1525: Invalid expression term 'string'
CheatSheetsCore.cs(61,80) : error CS1003: Syntax error, ',' expected

**Comment by IlliumIv** [comment]
Removed delegate initialization
